// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZV_K8pe5cYjH2IB6zzSZ4LzIyxDHxW8',
    appId: '1:22713666035:web:f04ad29e1444825da2ea86',
    messagingSenderId: '22713666035',
    projectId: 'wedme-b960a',
    authDomain: 'wedme-b960a.firebaseapp.com',
    storageBucket: 'wedme-b960a.appspot.com',
    measurementId: 'G-ER2P46S1YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1CL2EB6nT5FPtyYHuOQPW3J7o--Plozg',
    appId: '1:22713666035:android:459cb608725f4138a2ea86',
    messagingSenderId: '22713666035',
    projectId: 'wedme-b960a',
    storageBucket: 'wedme-b960a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhM11a_J248L_YqQD43YMmXsTpDdG1ESo',
    appId: '1:22713666035:ios:0cba149db30da932a2ea86',
    messagingSenderId: '22713666035',
    projectId: 'wedme-b960a',
    storageBucket: 'wedme-b960a.appspot.com',
    iosClientId: '22713666035-8p8ha2h992dr690ubh237n70raal4sn4.apps.googleusercontent.com',
    iosBundleId: 'com.briskita.wedme',
  );
}
